version: '3'

networks:
  upload-tests:
    driver: bridge

services:
  # Test Container for running tests locally
  local_tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - minio
      - dynamodb
      - pennsievedb
    environment:
      - DYNAMODB_URL=http://dynamodb:8000
      - MINIO_URL=http://minio:9000
      - POSTGRES_HOST=pennsievedb
      - MANIFEST_FILE_TABLE=manifest-file-table
      - MANIFEST_TABLE=manifest-table
      - IMPORTED_SNS_TOPIC=import-topic
    volumes:
      - $PWD:/go/src/github.com/pennsieve/upload-service-v2
      - $PWD/../pennsieve-go-core:/go/src/github.com/pennsieve/pennsieve-go-core
    networks:
      - upload-tests

  # CI Container for running tests on Jenkins
  ci_tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - dynamodb-ci
      - pennsievedb-ci
    environment:
      - DYNAMODB_URL=http://dynamodb-ci:8000
      - POSTGRES_HOST=pennsievedb-ci
      - MANIFEST_FILE_TABLE=manifest-file-table
      - MANIFEST_TABLE=manifest-table
      - IMPORTED_SNS_TOPIC=import-topic
    volumes:
      - $PWD:/go/src/github.com/pennsieve/upload-service-v2
    networks:
      - upload-tests

  # Local S3 Storage
  minio:
    image: minio/minio
    ports:
      - "9002:9000"
      - "9001:9001"
    volumes:
      - $PWD/testdata:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data
    networks:
      - upload-tests

  dynamodb:
    image: amazon/dynamodb-local
    restart: always
    volumes:
      - ./test-dynamodb-data:/home/dynamodblocal/data
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/"
    networks:
      - upload-tests

  dynamodb-ci:
    image: amazon/dynamodb-local
    restart: always
    volumes:
      - ./test-dynamodb-data:/home/dynamodblocal/data
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/"
    networks:
      - upload-tests

  pennsievedb:
    image: pennsieve/pennsievedb:V20230214167639-seed
    restart: always
    ports:
      - "5432:5432"
    networks:
      - upload-tests

  pennsievedb-ci:
    image: pennsieve/pennsievedb:V20230214167639-seed
    restart: always
    networks:
      - upload-tests


