openapi: 3.0.1
info:
  version: 1.0.0
  title: Pennsieve Go API
  description: Pennsieve Go Based Serverless API
components:
  x-amazon-apigateway-integrations:
    manifest-service:
      type: aws_proxy
      uri: ${upload_service_lambda_arn}
      httpMethod: POST
      passthroughBehavior: when_no_match
      contentHandling: CONVERT_TO_TEXT
      payloadFormatVersion: 2.0
  securitySchemes:
    pennsieve-cognito:
      type: "oauth2"
      flows: { }
      x-amazon-apigateway-authorizer:
        identitySource: "$request.header.Authorization"
        jwtConfiguration:
          audience:
            - ${user_pool_2_client_id}
          issuer: ${cognito_endpoint}
        type: "jwt"
paths:
  /manifest:
    get:
      x-amazon-apigateway-integration:
        $ref: '#/components/x-amazon-apigateway-integrations/manifest-service'
      operationId: createManifest
      summary: Get a list of active manifest for user
      security:
        - pennsieve-cognito: []
      requestBody:
      # ...
      responses:
        default:
          description: Success
    post:
      summary: Create a new upload manifest
      x-amazon-apigateway-integration:
        $ref: '#/components/x-amazon-apigateway-integrations/manifest-service'
      operationId: createManifest
      security:
        - pennsieve-cognito: [ ]
      requestBody:
        #...callbacks:
      responses:
        default:
          description: Success











